<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MiPrimeraAPI2Cuatrimestre.DAL\MiPrimeraAPI2Cuatrimestre.DAL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Modelos\" />
  </ItemGroup>

</Project>
